// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://exncsjdfynfpjrrzfxll.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV4bmNzamRmeW5mcGpycnpmeGxsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUxNTM1OTgsImV4cCI6MjA3MDcyOTU5OH0.YdYW-3HQ6JlMro49egqL-cRSZ3lklN676Zho4zj3R58";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});